import 'package:flutter_test/flutter_test.dart';
import 'package:shongi/features/doctors/data/consult_catalog_repository.dart';
import 'package:shongi/features/doctors/models/doctor.dart';

void main() {
  group('ConsultCatalogRepository', () {
    late List<Doctor> consults;

    setUp(() async {
      consults = await ConsultCatalogRepository().loadDoctors();
    });

    test('offers consult categories', () {
      expect(consults, isNotEmpty);
    });

    test('gives every entry a unique, non-empty id', () {
      final ids = consults.map((c) => c.id).toList();

      expect(ids.toSet().length, ids.length);
      expect(ids.every((id) => id.isNotEmpty), isTrue);
    });

    test('every entry explains what it covers and what to bring', () {
      for (final consult in consults) {
        expect(consult.about, isNotEmpty, reason: '${consult.id} has no about');
        expect(consult.bring, isNotEmpty, reason: '${consult.id} has no bring');
        expect(consult.tags, isNotEmpty, reason: '${consult.id} has no tags');
      }
    });

    test('no entry invents a practitioner name', () {
      // A "Dr. <surname>" entry would be presenting an invented person as real.
      for (final consult in consults) {
        expect(
          consult.name.startsWith('Dr.'),
          isFalse,
          reason: '${consult.id} looks like a named practitioner',
        );
      }
    });

    test('no entry carries a fabricated rating, fee or address', () {
      // The Doctor model no longer has rating/reviewCount/feePerVisit/location,
      // so this test documents that the fabricated fields are gone rather than
      // quietly removed.
      for (final consult in consults) {
        expect(consult.specialty, isNotEmpty);
        expect(consult.speciality, consult.specialty);
      }
    });

    test('entries never promise a specific availability time', () {
      // Slot times are generated by the booking screen from real per-day data,
      // so no catalogue entry may hard-code one.
      for (final consult in consults) {
        expect(consult.name.contains('AM'), isFalse);
        expect(consult.name.contains('PM'), isFalse);
      }
    });
  });
}
