// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRlyRv4pjbo0DSRSkcFAb_ZWzT0JbG2BY',
    appId: '1:394327746329:web:bbd745df1d98808e8a0788',
    messagingSenderId: '394327746329',
    projectId: 'shongi-8ed7e',
    authDomain: 'shongi-8ed7e.firebaseapp.com',
    storageBucket: 'shongi-8ed7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA07sGK1qpl1ClFrRKB4Y8zTNeR8_ViNR0',
    appId: '1:394327746329:android:c9fe95d2ad500e6b8a0788',
    messagingSenderId: '394327746329',
    projectId: 'shongi-8ed7e',
    storageBucket: 'shongi-8ed7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB37jvdKkm95jIHh4cHIhbDylZK_nmKS8w',
    appId: '1:394327746329:ios:5e7843b85e52c32a8a0788',
    messagingSenderId: '394327746329',
    projectId: 'shongi-8ed7e',
    storageBucket: 'shongi-8ed7e.firebasestorage.app',
    iosBundleId: 'com.example.shongi',
  );
}
